site_name: OpenSceneGraph 3.0 Cookbook
nav:
- Chapter 1: 'ch01.md'
- Chapter 2: 'ch02.md'
- Chapter 3: 'ch03.md'
- Chapter 4: 'ch04.md'
- Chapter 5: 'ch05.md'
- Chapter 6: 'ch06.md'
- Chapter 7: 'ch07.md'
- Chapter 8: 'ch08.md'
- Chapter 9: 'ch09.md'
theme: readthedocs